---
- name: download golang
  get_url:
    url: https://go.dev/dl/go1.23.3.linux-amd64.tar.gz
    checksum: sha256:a0afb9744c00648bafb1b90b4aba5bdb86f424f02f9275399ce0c20b93a2c3a8
    dest: /tmp/golang.tar.gz
  register: golang

- name: install golang
  unarchive:
    remote_src: yes
    src: /tmp/golang.tar.gz
    dest: /opt
  when: golang.changed

- name: add new golang to PATH
  blockinfile:
    path: /home/isucon/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK [bari-bari full throttle! CPU gang]"
    block: |
      export GOROOT=/opt/go
      export GOPATH=$HOME/go
      export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
